name: Test Build

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test-build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install Dependencies
        run: npm install
      - name: Build Project
        run: pnpm run build
